[package]
name          = "{{ project-name }}"
description   = "{{ project-name }}"
version       = "0.0.1"
edition       = "2024"
license       = "Apache-2.0"
readme        = "README.md"
homepage      = "https://github.com/{{ github_id }}/{{ project-name }}"
repository    = "https://github.com/{{ github_id }}/{{ project-name }}"
documentation = "https://github.com/{{ github_id }}/{{ project-name }}"
publish       = false

[dependencies]
anyhow                = { version = "1.0" }
{%- if config %}
configured            = { version = "0.9" }
{%- endif %}
{%- if otel %}
opentelemetry         = { version = "0.32" }
opentelemetry_sdk     = { version = "0.32" }
opentelemetry-otlp    = { version = "0.32", features = [ "grpc-tonic" ] }
{%- endif %}
{%- if config or otel %}
serde                 = { version = "1.0", features = [ "derive" ] }
serde_json            = { version = "1.0" }
{%- endif %}
tokio                 = { version = "1", features = [ "macros", "rt-multi-thread" ] }
tracing               = { version = "0.1" }
{%- if otel %}
tracing-opentelemetry = { version = "0.33" }
{%- endif %}
tracing-subscriber    = { version = "0.3", features = [ "env-filter", "fmt", "json" ] }
