services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.122.1
    restart: always
    command: 
      - --config
      - /etc/otel-collector-config.yaml
    environment:
      GRAFANA_OTLP_USERNAME: $GRAFANA_OTLP_USERNAME
      GRAFANA_OTLP_PASSWORD: $GRAFANA_OTLP_PASSWORD
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./target/filestorage:/var/lib/otelcol/file_storage
      - ./target/log:/var/log
    ports:
      - 4317:4317 # OTLP gRPC receiver
